# --- Experiment configurations --------------------------------------------------------------------

# experiment name, used as folder name
experiment_name: WaterSoft

# place to store run directory (if empty runs are stored in $cwd$/runs/)
run_dir: /home/jovyan/watersoft/results_LSTM_v3

# files to specify training, validation and test basins (relative to code root or absolute path)
train_basin_file: /home/jovyan/watersoft/Model/basin_list.txt
validation_basin_file: /home/jovyan/watersoft/Model/basin_list.txt
test_basin_file: /home/jovyan/watersoft/Model/test_list.txt


# training, validation and test time periods (format = 'dd/mm/yyyy')
train_start_date: '01/01/1980'
train_end_date: '31/12/2010'
validation_start_date: '01/01/2011'
validation_end_date: '31/12/2019'
test_start_date: '01/01/2020'
test_end_date: '31/12/2023'

# fixed seed, leave empty to use a random seed
seed: 123

# which GPU (id) to use [in format of cuda:0, cuda:1 etc, or cpu or None]
device: cuda:0

# --- Validation configuration ---------------------------------------------------------------------

# specify after how many epochs to perform validation
validate_every: 10

# specify how many random TG to use for validation
validate_n_random_basins: 10

# specify which metrics to calculate during validation (see codebase.evaluation.metrics)
metrics:
- RMSE
- Pearson-r
- NSE
- MSE
- KGE

# --- Model configuration --------------------------------------------------------------------------

# base model type [lstm, ealstm, cudalstm, embcudalstm, shortcutlstm, dropoutlstm, cudalstminitialh]
# (has to match the if statement in modelzoo/__init__.py)
model: ealstm

# prediction head [regression, mdn, umal]. Define the head specific parameters below
head: regression

# ----> General settings <----

# Number of cell states of the LSTM
hidden_size: 128

# Initial bias value of the forget gate
initial_forget_bias: 3

# Dropout applied to the output of the LSTM
output_dropout: 0.2

output_activation: linear

# --- Training configuration -----------------------------------------------------------------------

# specify optimizer [Adam, Adadelta]
optimizer: Adam

# specify loss [MSE, NSE, RMSE, UMALLoss, MDNLoss]
loss: NSE

# specify learning rates to use starting at specific epochs (0 is the initial learning rate)
learning_rate:
    0: 1e-3
    1: 5e-4

# Mini-batch size
batch_size: 256

# Number of training epochs
epochs: 50

# If True, clips norm of gradients
clip_gradient_norm: 1

# Defines which time steps are used to calculate the loss. Can't be larger than seq_length
predict_last_n: 1

# Length of the input sequence
seq_length: 30

# Number of parallel workers used in the data pipeline
num_workers: 0

# Log the training loss every n steps
log_interval: 5

# If true, writes logging results into tensorboard file
log_tensorboard: True

# Save model weights every n epochs
save_weights_every: 1

# Store the results of the validation to disk
save_validation_results: True

# --- Data configurations --------------------------------------------------------------------------

dataset: generic

# Path to data set
data_dir: /home/jovyan/watersoft/Data

# variables to use as time series input (names match the data file column headers)
dynamic_inputs:
- prcp
- tmax

# which columns to use as target
target_variables:
- streamflow

static_attributes:
  - p_mean
  - pet_mean
  - p_seasonality
  - frac_snow
  - aridity
  - high_prec_freq
  - high_prec_dur
  - low_prec_freq
  - low_prec_dur
  - glim_1st_class_frac
  - glim_2nd_class_frac
  - geol_permeability
  - q_mean
  - runoff_ratio
  - slope_fdc
  - baseflow_index
  - stream_elas
  - q5
  - q95
  - high_q_freq
  - high_q_dur
  - low_q_freq
  - low_q_dur
  - hfd_mean
  - huc_02
  - soil_depth_pelletier
  - soil_depth_statsgo
  - soil_porosity
  - soil_conductivity
  - max_water_content
  - sand_frac
  - silt_frac
  - clay_frac
  - other_frac
  - gauge_lat
  - gauge_lon
  - elev_mean
  - slope_mean
  - area_gages2
  - area_geospa_fabric
  - frac_forest
  - lai_max
  - lai_diff
  - gvf_max
  - gvf_diff
  - dom_land_cover_frac
  - root_depth_50
  - root_depth_99